### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kaganjd** [kaganjd/gitmo#1]
- [ ] instead of showing all names, show each name with its history
- [ ] figure out text highlight color + text color
- [ ] make this happen
- frame 1: name 1, history 1, glitch 1
- frame 2: name 1, history 1, glitch transition
- frame 3: name 2, history 2, glitch 2
- frame 4: name 2, history 2, glitch transition
etc.
in a loop

EXTRA CREDIT
- [ ] create my own glitched gradhat image where image glitch is related to inmate # (see this lib: https://github.com/snorpey/glitch-canvas)
